# Generated by Django 4.1.1 on 2022-09-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Skill_2", new_name="Skill",),
        migrations.DeleteModel(name="Skill_1",),
        migrations.DeleteModel(name="Skill_3",),
        migrations.DeleteModel(name="Skill_4",),
        migrations.DeleteModel(name="Skill_5",),
        migrations.DeleteModel(name="Skill_6",),
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name": "Skill", "verbose_name_plural": "Skills"},
        ),
    ]
