# Generated by Django 4.1.1 on 2022-09-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_rename_skill_2_skill_delete_skill_1_delete_skill_3_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personal", old_name="name", new_name="project_name",
        ),
        migrations.RenameField(
            model_name="sefphotograph",
            old_name="description",
            new_name="photo_caption",
        ),
        migrations.RenameField(
            model_name="sefphotograph", old_name="name", new_name="photo_name",
        ),
        migrations.RenameField(
            model_name="skill", old_name="name", new_name="name_of_skill",
        ),
        migrations.RenameField(
            model_name="socialmedia", old_name="IG_link", new_name="Facbook_link",
        ),
        migrations.RenameField(
            model_name="socialmedia", old_name="fb_link", new_name="Instagram_link",
        ),
        migrations.RenameField(
            model_name="socialmedia", old_name="twitter_link", new_name="Twitter_link",
        ),
        migrations.RenameField(
            model_name="webdevelopment", old_name="name", new_name="project_name",
        ),
        migrations.AlterField(
            model_name="about", name="age", field=models.IntegerField(max_length=10),
        ),
    ]
