# Generated by Django 4.1.1 on 2022-09-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_rename_name_personal_project_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about", name="age", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="skill", name="pct", field=models.CharField(max_length=10),
        ),
    ]
