# Generated by Django 4.1.1 on 2022-09-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_remove_socialmedia_twitter_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="education",
            name="institute",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="education",
            name="qualification",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company_name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="experience", name="role", field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="personal",
            name="description",
            field=models.CharField(max_length=150),
        ),
    ]
