# Generated by Django 4.1.1 on 2022-10-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_alter_education_degree_alter_education_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="education", name="start_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="experience", name="start_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="webdevelopment",
            name="description",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="webdevelopment",
            name="project_name",
            field=models.CharField(max_length=50),
        ),
    ]
